import os
import textwrap
from pathlib import Path


def _site_relative_url(src: str, docs_dir: str, page_dest_uri: str) -> str:
    """Convert a project-root-relative asset path to a URL relative to the served page.

    Files under ``docs_dir`` are served from the site root, so the docs_dir
    prefix is stripped and the result re-expressed relative to the page being
    rendered. This avoids hard-to-read, page-relative
    ``../../../../../_figs/...`` links in the page source: callers pass a
    repo-root-relative path and the macro works out the URL.

    Parameters
    ----------
    src : str
        Path to the asset, relative to the project root
        (e.g. "docs/_figs/my_plot.png").
    docs_dir : str
        The mkdocs ``docs_dir`` (``env.conf["docs_dir"]``).
    page_dest_uri : str
        Destination URI of the page being rendered
        (``env.page.file.dest_uri``).
    """
    site_path = Path(src).resolve().relative_to(Path(docs_dir).resolve())
    return os.path.relpath(site_path, Path(page_dest_uri).parent)


def define_env(env):
    @env.macro
    def api_link(text, module_path):
        """
        Macro generated by Claude to allow different handling of api links depending on whether api-autonav is enabled
        The goal is to allow us to run without api-autonav in CI, since api-autonav is very slow, while still using it on deployment.

        Return a cross-reference link to API docs, or plain text when api-autonav is disabled.

        When ENABLE_API_AUTONAV is set, returns ``[text][module_path]`` so that
        mkdocs-autorefs resolves the link normally.  Otherwise, validates that
        the corresponding source file (or package) exists and returns the text
        without a link so the build can proceed in strict mode.
        """
        parts = module_path.split(".")
        # Try as a module file first, then as a package directory
        file_path = Path(*parts).with_suffix(".py")
        package_path = Path(*parts) / "__init__.py"
        # For function-level refs like mod.func, check the module part
        parent_file = Path(*parts[:-1]).with_suffix(".py") if len(parts) > 1 else None

        if not (
            file_path.exists()
            or package_path.exists()
            or (parent_file and parent_file.exists())
        ):
            raise FileNotFoundError(
                f"api_link: module path '{module_path}' does not correspond to "
                f"any existing file (checked {file_path}, {package_path}"
                + (f", {parent_file})" if parent_file else ")")
            )

        if os.environ.get("ENABLE_API_AUTONAV"):
            return f"[{text}][{module_path}]"
        return text

    @env.macro
    def include_file(path):
        """Include the contents of an external file, raising an error if it does not exist.

        Parameters
        ----------
        path : str
            Path to the file to include, relative to the project root.
        """
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"include_file: '{path}' does not exist")
        return file_path.read_text()

    @env.macro
    def markdown_table(src, title="Table", collapse_threshold=50):
        """Include a programmatically-generated markdown table, collapsing large ones.

        Like :func:`include_file`, this returns the raw markdown of a `.mdx`
        table file (resolved relative to the project root) so mkdocs renders it
        as a table. When the table has ``collapse_threshold`` or more data rows
        it is wrapped in a closed ``??? info`` admonition so long tables don't
        dominate the page.

        The ``{{ markdown_table(...) }}`` call must start at column 0: the
        returned block-level admonition/table only parses correctly at the left
        margin (an indented call would turn the first output line into a code
        block). This is enforced --- an indented call fails the build (see
        ``_assert_macro_call_at_margin``) rather than silently mis-rendering.

        Parameters
        ----------
        src : str
            Path to the `.mdx` table file, relative to the project root
            (e.g. "docs/_figs/my_table.mdx").
        title : str
            Title shown on the collapsible block (only used when the table is
            large enough to be collapsed).
        collapse_threshold : int
            Minimum number of data rows (excluding the header and separator
            rows) at which the table is wrapped in a collapsible block.
        """
        file_path = Path(src)
        if not file_path.is_file():
            raise FileNotFoundError(
                f"markdown_table: '{src}' does not exist "
                f"(referenced from page '{env.page.file.src_uri}')"
            )
        text = file_path.read_text()

        # A markdown table is a header row + a separator row + one row per record;
        # every one of those lines starts with "|". Subtract the header and
        # separator to get the data-row count.
        table_lines = [ln for ln in text.splitlines() if ln.lstrip().startswith("|")]
        n_rows = max(len(table_lines) - 2, 0)

        if n_rows >= collapse_threshold:
            body = textwrap.indent(text, "    ")
            return f'??? info "{title}"\n\n{body}'
        return text

    @env.macro
    def png_embed(src, alt="", caption=""):
        """
        Embed a PNG (or other static image) using a path relative to the project
        root, mirroring :func:`plotly_embed` so that static and interactive
        figures are referenced the same way.

        This avoids the hard-to-read, page-relative ``![](../../../../../_figs/...)``
        links: callers pass a repo-root-relative path
        (e.g. "docs/_figs/my_plot.png") and the macro resolves the URL relative
        to the served page itself.

        Parameters
        ----------
        src : str
            Path to the image file, relative to the project root
            (e.g. "docs/_figs/my_plot.png").
        alt : str
            Alt text for the image.
        caption : str
            Optional caption rendered as a <figcaption> below the image. When
            provided the image is wrapped in a <figure>.
        """
        if not Path(src).is_file():
            raise FileNotFoundError(
                f"png_embed: '{src}' does not exist "
                f"(referenced from page '{env.page.file.src_uri}')"
            )

        relative_url = _site_relative_url(
            src, env.conf["docs_dir"], env.page.file.dest_uri
        )

        # Use max-width (not width) so the image renders at its natural size and
        # only shrinks when it would overflow the page — matching how a plain
        # markdown ``![](...)`` image behaves under Material's default CSS.
        img = f'<img src="{relative_url}" alt="{alt}" style="max-width:100%; height:auto;">'
        if caption:
            return (
                f'<figure style="margin:0;">\n'
                f"{img}\n"
                f'<figcaption style="text-align:center; font-style:italic; margin-top:0.5em;">{caption}</figcaption>\n'
                f"</figure>"
            )
        return img

    @env.macro
    def plotly_embed(src, id, height="775px", caption=""):
        """
        This is a macro function added by Claude to allow the embedding of plotly plots which can be expanded to full screen.

        Embed a Plotly HTML file with a fullscreen button.

        Parameters
        ----------
        src : str
            Path to the Plotly HTML file, relative to the project root
            (e.g. "docs/_figs/my_plot.html").
        id : str
            A unique HTML id for the iframe (must be unique per page).
        height : str
            CSS height of the embedded iframe, e.g. "750px" or "60vh".
        caption : str
            Optional caption rendered as a <figcaption> below the iframe.
            Supports inline HTML. When provided the whole embed is wrapped in
            a <figure> with width:100% so the iframe is never squished.
        """
        if not Path(src).is_file():
            raise FileNotFoundError(
                f"plotly_embed: '{src}' does not exist "
                f"(referenced from page '{env.page.file.src_uri}')"
            )

        relative_url = _site_relative_url(
            src, env.conf["docs_dir"], env.page.file.dest_uri
        )

        button = (
            f'<div style="display:flex; justify-content:flex-end; margin:.25rem 0;">\n'
            f"<button onclick=\"document.getElementById('{id}').requestFullscreen()\"\n"
            f'  style="cursor:pointer; background:none; border:1px solid #ccc; padding:4px 12px; border-radius:4px;">\n'
            f"  Fullscreen Plot &#x2922;\n"
            f"</button>\n"
            f"</div>\n"
        )
        iframe = (
            f"<iframe\n"
            f'  id="{id}"\n'
            f'  src="{relative_url}"\n'
            f'  style="width:100%; height:{height}; border:none;"\n'
            f"  allowfullscreen></iframe>"
        )
        if caption:
            return (
                f'<div style="width:100%; margin:0;">\n'
                f"{button}"
                f"{iframe}\n"
                f'<p style="width:100%; text-align:center; font-style:italic; margin-top:0.5em;">{caption}</p>\n'
                f"</div>"
            )
        return button + iframe

    @env.macro
    def ppp_rg_data_table(src, id, height="775px", precision=4):
        return data_table(
            src=src,
            id=id,
            height=height,
            precision=precision,
            caption=PPP_RG_DATA_TABLE_CAPTION,
        )

    @env.macro
    def susie_polyfun_explain_plot(
        src,
        alt="",
    ):
        return png_embed(src=src, alt=alt, caption=SUSIE_POLYFUN_EXPLAIN_PLOT_CAPTION)

    @env.macro
    def susie_polyfun_data_table(src, id, height="775px", precision=4):
        return data_table(
            src=src,
            id=id,
            height=height,
            precision=precision,
            caption=SUSIE_POLYFUN_EXPLAIN_TABLE_CAPTION,
        )

    @env.macro
    def susie_polyfun_variant_detail_table(src, id, height="775px", precision=4):
        return data_table(
            src=src,
            id=id,
            height=height,
            precision=precision,
            caption=SUSIE_POLYFUN_VARIANT_DETAIL_TABLE_CAPTION,
        )

    @env.macro
    def data_table(src, id, height="600px", precision=4, caption=""):
        """Embed a large tabular asset as a sortable, filterable, virtualised table.

        For tables too large for markdown_table --- which renders every row into
        the page DOM at build time, and becomes unworkable in the thousands ---
        this instead ships the data as a parquet asset and renders it client-side
        with Tabulator. Only the visible rows exist in the DOM, so row count
        barely affects page weight.

        Parquet rather than CSV because the values stay exactly as the build
        system produced them: full precision, no rounding decision baked
        into the published file. Displayed values are rounded to ``precision``
        for legibility, but the underlying data --- and therefore the table's
        CSV download button --- remains exact.

        The parquet should be written with the integer columns as Int32. Parquet
        INT64 decodes to JavaScript BigInt, which Tabulator cannot format; the
        script below coerces BigInt defensively, but doing it at the source
        avoids relying on that.

        Like markdown_table, the ``{{ data_table(...) }}`` call must start at
        column 0, since an indented block-level HTML element is reinterpreted as
        an indented code block.

        Parameters
        ----------
        src : str
            Path to the parquet file, relative to the project root
            (e.g. "docs/_figs/my_table.parquet").
        id : str
            A unique HTML id for the table container (must be unique per page).
        height : str
            CSS height of the table viewport, e.g. "600px". Virtualisation keys
            off this, so it must be a fixed height rather than "auto".
        precision : int
            Decimal places used when *displaying* non-integer values. Does not
            affect the underlying data or the CSV download.
        caption : str
            Optional caption rendered below the table.
        """
        if not Path(src).is_file():
            raise FileNotFoundError(
                f"data_table: '{src}' does not exist "
                f"(referenced from page '{env.page.file.src_uri}')"
            )

        relative_url = _site_relative_url(
            src, env.conf["docs_dir"], env.page.file.dest_uri
        )
        download_name = Path(src).with_suffix(".csv").name

        # Built by token substitution rather than an f-string: the script is
        # dense with JS object literals, and doubling every brace to escape them
        # would make it unreadable.
        script = _DATA_TABLE_SCRIPT
        for token, value in (
            ("__TABLE_ID__", id),
            ("__DATA_URL__", relative_url),
            ("__PRECISION__", str(precision)),
            ("__DOWNLOAD_NAME__", download_name),
            ("__HEIGHT__", height),
        ):
            script = script.replace(token, value)

        caption_html = (
            f'<p style="width:100%; text-align:center; font-style:italic; '
            f'margin-top:0.5em;">{caption}</p>\n'
            if caption
            else ""
        )
        return (
            f'<div style="display:flex; justify-content:flex-end; margin:.25rem 0;">\n'
            f'<button id="{id}-download"\n'
            f'  style="cursor:pointer; background:none; border:1px solid #ccc; '
            f'padding:4px 12px; border-radius:4px;">\n'
            f"  Download CSV &#x2913;\n"
            f"</button>\n"
            f"</div>\n"
            f'<div id="{id}" style="height:{height};">'
            f'<em id="{id}-status">Loading table…</em></div>\n'
            f"{caption_html}"
            f"{script}"
        )


# Client-side loader for :func:`data_table`. Tabulator itself is loaded globally
# via extra_javascript in mkdocs.yml (it ships UMD, so it lands on window);
# hyparquet is ESM-only and so is imported here from a CDN that serves it as a
# browser-consumable module.
_DATA_TABLE_SCRIPT = """<script type="module">
(async () => {
  const container = document.getElementById("__TABLE_ID__");
  const status = document.getElementById("__TABLE_ID__-status");
  try {
    const { parquetReadObjects } = await import("https://esm.sh/hyparquet@1.26.2");
    const { compressors } = await import("https://esm.sh/hyparquet-compressors@1.1.1");

    const response = await fetch("__DATA_URL__");
    if (!response.ok) throw new Error(`fetch failed: ${response.status}`);
    const rows = await parquetReadObjects({
      file: await response.arrayBuffer(),
      compressors,
    });

    // Parquet INT64 decodes to BigInt, which Tabulator cannot format (it throws
    // and silently renders zero rows). Coerce to Number; the magnitudes in these
    // tables are far inside the safe-integer range.
    for (const row of rows) {
      for (const key in row) {
        if (typeof row[key] === "bigint") row[key] = Number(row[key]);
      }
    }

    // Round only for display. The value Tabulator holds --- and downloads ---
    // stays exact, and sorting still compares the underlying numbers.
    const display = (cell) => {
      const value = cell.getValue();
      if (typeof value !== "number" || Number.isInteger(value)) return value;
      // toFixed collapses anything smaller than the last retained decimal place
      // to "0.0000", which is where p-values live. Switch to exponential so the
      // magnitude survives; exact zero stays fixed, since "0.000e+0" is noise.
      if (value !== 0 && Math.abs(value) < 10 ** -__PRECISION__) {
        return value.toExponential(Math.max(__PRECISION__ - 1, 0));
      }
      return value.toFixed(__PRECISION__);
    };

    const table = new Tabulator(container, {
      data: rows,
      // Must be a concrete CSS length, not "100%": Tabulator only virtualises
      // when it can resolve the viewport height, and silently falls back to
      // rendering every row when it cannot.
      height: "__HEIGHT__",
      layout: "fitDataFill",
      autoColumns: true,
      autoColumnsDefinitions: (definitions) =>
        definitions.map((definition) => {
          const sample = rows[0][definition.field];
          const numeric = typeof sample === "number";
          return {
            ...definition,
            headerFilter: numeric ? "number" : "input",
            headerFilterFunc: numeric ? ">=" : "like",
            headerFilterPlaceholder: numeric ? ">=" : "filter",
            sorter: numeric ? "number" : "string",
            formatter: numeric ? display : undefined,
          };
        }),
    });

    table.on("tableBuilt", () => status?.remove());
    document
      .getElementById("__TABLE_ID__-download")
      .addEventListener("click", () => table.download("csv", "__DOWNLOAD_NAME__"));
  } catch (error) {
    // Surface failures in the page rather than only the console, so a broken
    // table is obvious when reviewing docs.
    if (status) status.textContent = `Failed to load table: ${error.message}`;
    throw error;
  }
})();
</script>"""


PPP_RG_DATA_TABLE_CAPTION = "Columns: oid: Olink assay ID; gene: name of gene/protein under study; rg: CT-LDSC genetic correlation estimate; rg_se: jackknife standard error of CT-LDSC genetic correlation estimate; rg_p: p value of test that rg is not zero; gcov: estimated genetic covariance; inter: intercept term in CT-LDSC regression; h2_trait: trait heritability estimate; h2_prot: protein heritability estimate; n_snps: number of hapmap3 variants included; spr: for cases in which multiple rows corresponding to distinct Olink assays of the same protein have been merged into a single row, this gives the maximum spread between the rg values of the merged rows; s_bh: True if the null hypothesis is rejected under the Benjamini-Hochberg procedure at an FDR of 0.05; s_bon: True if the null hypothesis is rejected under the Bonferroni correction at a significance level of 0.05."

SUSIE_POLYFUN_EXPLAIN_PLOT_CAPTION = "Plot illustrating results of applying SUSIE with a polyfun prior to a GWAS locus.  First panel: Manhattan plot of locus with overlaid recombination rate data.  Second panel: PIPs from SUSIE run with uniform prior.  Third panel: PIPs from SUSIE run with PolyFun prior; Callouts: variants with the highest PIPs in the PolyFun-prior SUSIE run are marked with callouts, which also indicate the key annotation families for these variants. Fourth Panel: genes at locus."

SUSIE_POLYFUN_EXPLAIN_TABLE_CAPTION = "Columns: chr: chromosome; pos: hg19 genomic position; ea: effect allele; nea: non-effect allele; cs_pf: credible set number in PolyFun-prior run; cs_u: credible set number in uniform-prior run; pip_pf: PIP (Posterior Inclusion Probability) in PolyFun-prior SUSIE run; pip_u: PIP in uniform-prior SUSIE run; lift: proportional increase in prior weight when switching from uniform prior to PolyFun prior; annot_X: Approximate contribution of annotation family X to PolyFun prior minus averaged contribution of annotation family X over all variants selected by uniform-prior SUSIE run."


SUSIE_POLYFUN_VARIANT_DETAIL_TABLE_CAPTION = "Columns: family: name of high-level annotation family; annotation: granular annotation name; gamma: regression coefficient of PolyFun prior weight on granular annotation, which indicates the extent to which the annotation can affect the prior. alpha_bar: PIP-weighted mean value of this annotation across all variants in uniform-prior SUSIE credible sets, which can be used as a baseline against which to compare the annotation values of key variants.  other columns: the values of all annotations for key variants under consideration."
