name: deploy_docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - uses: actions/cache@v6
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - uses: prefix-dev/setup-pixi@v0.10.2
        name: Setup Pixi Environment
        with:
          pixi-version: v0.80.0
          cache: true
      - run: pixi r invoke pfig
        name: Download figures
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAVE_GH_TOKEN: "True"
      - run: pixi r mkdocs build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAVE_GH_TOKEN: "True"
          ENABLE_API_AUTONAV: "True"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5